# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Christopher West <cwest@thedigitaledge.co.uk>

CONFIG_CONSOLE=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_UART_CONSOLE=y
CONFIG_CRC=y
CONFIG_MODEM_XMODEM=y
CONFIG_MODEM_XMODEM_BLOCK_SIZE_1024=y
CONFIG_MODEM_XMODEM_USE_CRC=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
